server {
    listen 80;
    server_name front.aribadevops.site back.aribadevops.site ats.aribadevops.site;
    return 301 https://$host$request_uri;
}

# Frontend
server {
    listen 443 ssl;
    server_name front.aribadevops.site;

    ssl_certificate /etc/nginx/certs/front.aribadevops.site/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/front.aribadevops.site/privkey.pem;

    location / {
        proxy_pass http://host.docker.internal:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Backend
server {
    listen 443 ssl;
    server_name back.aribadevops.site;

    ssl_certificate /etc/nginx/certs/back.aribadevops.site/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/back.aribadevops.site/privkey.pem;

    location / {
        proxy_pass http://host.docker.internal:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Python ATS
server {
    listen 443 ssl;
    server_name ats.aribadevops.site;

    ssl_certificate /etc/nginx/certs/ats.aribadevops.site/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/ats.aribadevops.site/privkey.pem;

    location / {
        proxy_pass http://host.docker.internal:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
